### ISSUE TITLE
Setup flutter_launcher_icons by default

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#121]
For most projects this will be enough & it is easy to configure different app icons per flavor

https://pub.dev/packages/flutter_launcher_icons

![image](https://user-images.githubusercontent.com/21172855/102717008-dd210100-42df-11eb-8958-469814db8997.png)

```
flutter_icons:
  image_path_android: "assets_launcher_icons/prod/android.png"
  image_path_ios: "assets_launcher_icons/prod/ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#CB2E63" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets_launcher_icons/foreground.png" # only available for Android 8.0 devices and above
```
