### ISSUE TITLE
Update fastlane to also check .g.dart files in analyze

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#245]
```
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_brace_in_string_interps: false
    avoid_returning_null_for_void: false
    prefer_inlined_adds: false
    prefer_const_declarations: false

```

![image](https://user-images.githubusercontent.com/21172855/162035515-6b99b3b6-a26d-4959-8f86-d897ac70a548.png)
```

    sh("mv", "analysis_options.yaml", "fastlane/analysis_options_original.yaml")
    sh("cp", "fastlane/analysis_options_all_files.yaml", "analysis_options.yaml")
    sh("fvm", "flutter", "analyze")
    sh("mv", "fastlane/analysis_options_original.yaml", "analysis_options.yaml")
    sh("fvm", "flutter", "analyze")
```
