### ISSUE TITLE
Update `analysis_options_all_files.yaml`

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-template#258]
```
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/util/license.dart'
  errors:
    unused_import: ignore
    unused_element: ignore
    unused_local_variable: ignore

linter:
  rules:
    unnecessary_brace_in_string_interps: false
    avoid_returning_null_for_void: false
    prefer_inlined_adds: false
    prefer_const_declarations: false
```
